#!/bin/sh
set -e
NETWORK=${NETWORK:-"kazoo"}
KAZOO_NODE="kazoo_apps@${HOSTNAME}"
export KZname="-name ${KAZOO_NODE}"
export KAZOO_CONFIG="${KAZOO_CONFIG:-"${HOME}/config.ini"}"
export RELX_REPLACE_OS_VARS=true
export KAZOO_APPS="${KAZOO_APPS:-"sysconf,blackhole,callflow,cdr,conference,crossbar,fax,hangups,media_mgr,milliwatt,omnipresence,pivot,registrar,reorder,stepswitch,teletype,trunkstore,webhooks,ecallmgr"}"

${HOME}/bin/kazoo "$*"
