#!/bin/sh
set -e
COMMAND="remote_console"
NETWORK=${NETWORK:-"kazoo"}
KAZOO_NODE="kazoo_apps@${HOSTNAME}"
export KZname="-name ${KAZOO_NODE}"
export RELX_REPLACE_OS_VARS=true
${HOME}/bin/kazoo $COMMAND "$*"
